### Teste da API Jira

POST http://localhost:3000/jira
Content-Type: application/json

{
  "issue": {
    "key": "TASK-154",
    "fields": {
      "summary": "Criar integração com Telegram"
    }
  },
  "changelog": {
    "items": [
      {
        "field": "status",
        "fromString": "Fazendo",
        "toString": "Testes"
      }
    ]
  }
}