### Local (npm run dev)
POST http://localhost:3000/jira
Content-Type: application/json

{
  "issue": {
    "key": "TASK-154",
    "summary": "Integração Telegram",
    "assignee": "Welder",
    "status": "Testes"
  },
  "transition": {
    "from": "Fazendo",
    "to": "Testes"
  },
  "url": "https://seudominio.atlassian.net/browse/TASK-154"
}

### Produção (Render)
POST https://bot-a5mj.onrender.com/jira
Content-Type: application/json

{
  "issue": {
    "key": "TASK-154",
    "summary": "Integração Telegram",
    "assignee": "Welder",
    "status": "Publicado"
  },
  "transition": {
    "from": "Pronto para Deploy",
    "to": "Publicado"
  },
  "url": "https://seudominio.atlassian.net/browse/TASK-154"
}
